name:                futr2
version:             0.1.0.0
github:              "ZenenTreadwell/futr2"
license:             BS
author:              "Taylor Singleton-Fookes"
maintainer:          "Zenen Treadwell"
copyright:           "2024"

extra-source-files:
- README.md
- CHANGELOG.md

description: "Types for nostr with relay"      

dependencies:
- base >= 4.19 && < 5

## control
- time
- entropy
- memory 
- mtl
- transformers
- stm 
- async  
- directory
- config-ini
- regex-tdfa

## data
- text
- vector
- bytestring-to-vector 
- bytestring
- containers
- aeson
- base16-bytestring
- base64-bytestring
- bech32

## network 
- wuss
- websockets
- warp 
- wai
- wai-websockets
- servant 
- servant-server
- req
- modern-uri

## crypto
- cryptonite
- cryptohash-sha256

## display 
- monomer
- JuicyPixels
- diagrams-lib
- diagrams-rasterific
- diagrams-core
- diagrams-contrib  
- Rasterific 

## database
- beam-core
- beam-sqlite
- beam-migrate
- sqlite-simple
# - beam-postgres
# - postgresql-simple

## test
- hspec
- QuickCheck

pkg-config-dependencies:
- libsecp256k1

language: GHC2021

default-extensions: 
- RecordWildCards
- ViewPatterns
- BlockArguments
- OverloadedStrings
- LambdaCase
- DataKinds
- DeriveGeneric 
- MultiParamTypeClasses
- FlexibleInstances
- FlexibleContexts
- NamedFieldPuns
- ScopedTypeVariables 
- TypeApplications
- TypeFamilies
- RankNTypes
- ForeignFunctionInterface
- EmptyDataDecls
- DoAndIfThenElse
- TupleSections
- QuasiQuotes
- ConstraintKinds
- PartialTypeSignatures

ghc-options:
- -Wall
- -fno-warn-orphans

library:
  source-dirs: src

executables:
  futr:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2
  relay:
    main: Main.hs
    source-dirs: relay
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2

tests:
  futr2-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - futr2
