
resolver: nightly-2024-01-17

packages:
- .

extra-deps:
- clplug-0.4.0.0
- monomer-1.6.0.1
- beam-core-0.10.1.0
- beam-sqlite-0.5.3.0
# - beam-postgres-0.5.3.1
- beam-migrate-0.5.2.1
- diagrams-contrib-1.4.5.1
- diagrams-lib-1.4.6
- diagrams-rasterific-1.4.2.3
- sdl2-2.5.5.0
- vector-sized-1.5.0
- cubicbezier-0.6.0.7
- finite-typelits-0.1.6.0
- force-layout-0.4.0.6
- vector-space-0.16
- MemoTrie-0.6.11
- newtype-generics-0.6.2
